new component
avramenkop/first-config pull request #1
Opened 2019-08-24 14:48 UTC by avramenkop

2019-08-26 17:08 UTC, IhorHarashchuk commented on tasks/task5/src/index.js
> +import './index.css';
Импортируй стили всегда после скриптов

2019-08-26 17:08 UTC, IhorHarashchuk commented on tasks/task5/src/serviceWorker.js
> +// This optional code is used to register a service worker.
этот файл пока нам не нужен - удали его

2019-08-26 17:08 UTC, IhorHarashchuk commented on tasks/task5/src/App.js
> +const App = (
Обычно  компонент  <App/> - содержит верхнеуровневую логику - поэтому вынеси реализауию Cars в отдельный компонент и импортируй сюда

2019-08-26 17:08 UTC, IhorHarashchuk commented on tasks/task5/src/App.js
> +function Cars (props) {
Для написания stateless компонент используй стрелочные функции. Почитай чем стрелочные отличаются от декларативных function  https://programmingwithmosh.com/react/react-functional-components/

2019-08-26 17:08 UTC, IhorHarashchuk commented on tasks/task5/src/App.css
> +.card {
если это связанные сузности cars и card  - то лучше именовать - типа   cars, car или  cars__list, car

2019-08-26 17:08 UTC, IhorHarashchuk commented on tasks/task5/src/App.css
> +  height: 500px;
Жесткое задание размеров картинки можем привести к тому что она искахится - если тебе прийдет картинка с другими размерами 100 на 200 например. Поэтому вобычно врапают и дают конкретные значения враперу а картинка windth:100 height: autk - как то так

2019-08-26 17:08 UTC, IhorHarashchuk commented on tasks/task5/src/App.js
> +          <div className="img">
лучше называть связанными сущностями типа -  card-image(car-image)

2019-08-26 17:08 UTC, IhorHarashchuk commented on tasks/task5/src/App.js
> +        <Cars car={{name: cars[0].name, year: cars[0].year, price: cars[0].price,
Примени метод map для перебора елементов массива

2019-08-27 17:44 UTC, avramenkop commented on tasks/task5/src/index.js
> +import './index.css';
готово

2019-08-27 17:44 UTC, avramenkop commented on tasks/task5/src/serviceWorker.js
> +// This optional code is used to register a service worker.
готово

2019-08-27 17:44 UTC, avramenkop commented on tasks/task5/src/App.js
> +const App = (
готово

2019-08-27 17:44 UTC, avramenkop commented on tasks/task5/src/App.js
> +function Cars (props) {
готово

2019-08-27 17:44 UTC, avramenkop commented on tasks/task5/src/App.css
> +.card {
готово

2019-08-27 17:44 UTC, avramenkop commented on tasks/task5/src/App.css
> +  height: 500px;
готово

2019-08-27 17:44 UTC, avramenkop commented on tasks/task5/src/App.js
> +          <div className="img">
готово

2019-08-27 17:44 UTC, avramenkop commented on tasks/task5/src/App.js
> +        <Cars car={{name: cars[0].name, year: cars[0].year, price: cars[0].price,
готово

2019-08-27 19:33 UTC, IhorHarashchuk requested changes

2019-08-27 19:33 UTC, IhorHarashchuk commented on tasks/task5/public/index.html
> +
Создай root вместо cars - обычное приложение гараздо больше чем   cars. Обобщай больше

2019-08-27 19:33 UTC, IhorHarashchuk commented on tasks/task5/src/index.js
> +ReactDOM.render(App, document.getElementById('cars'));
Тут соответственно  root или можешь назвать v-root

2019-08-27 19:33 UTC, IhorHarashchuk commented on tasks/task5/src/Cars.js
> +let cars = [
1 - создай компоненту CarsPage.js
2 - В нее вынеси свой массив
3 - В этой же компоненте странице - Импортируй Car (не Cars - потому что если ты называешь Cars - это уже готовый список - а это не так) - и проитерируй его с массивом

2019-08-27 19:33 UTC, IhorHarashchuk commented on tasks/task5/src/App.js
> +import {cars, Cars} from './Cars';
1. Старайся не именовать массив и компонент настолько похоже - компоненту лучше назвать  Car - в соответствии с тем что она делает - она не список поэтому не Cars  f  Car - (по под стайлу)
2. Массив с машинами лучше назвать типа carModel или carList - назови более понятнее про что это/

2019-08-27 19:33 UTC, IhorHarashchuk commented on tasks/task5/src/App.css
> +#cars {
Луше именовать стили классами

2019-08-27 20:56 UTC, avramenkop commented on tasks/task5/public/index.html
> +
есть

2019-08-27 20:56 UTC, avramenkop commented on tasks/task5/src/index.js
> +ReactDOM.render(App, document.getElementById('cars'));
есть

2019-08-27 20:56 UTC, avramenkop commented on tasks/task5/src/Cars.js
> +let cars = [
?

2019-08-27 20:56 UTC, avramenkop commented on tasks/task5/src/App.js
> +import {cars, Cars} from './Cars';
есть

2019-08-27 20:56 UTC, avramenkop commented on tasks/task5/src/App.css
> +#cars {
есть

2019-08-27 20:59 UTC, IhorHarashchuk approved these changes

2019-08-27 21:04 UTC, IhorHarashchuk requested changes

2019-08-27 21:04 UTC, IhorHarashchuk commented on tasks/task5/public/index.html
> +<div class="root"></div>
тут к сожалению нужен id - потому что это точка входа в дом дерево

2019-08-27 21:04 UTC, IhorHarashchuk commented on tasks/task5/src/Cars.js
> +import './App.css';
файлик переназови - это ж стили к Car?

2019-08-27 21:04 UTC, IhorHarashchuk commented on tasks/task5/src/CarsPage.js
> +export {CarsPage};
export  можно делать сразу - типа export const CarsPage

2019-08-27 21:04 UTC, IhorHarashchuk commented on tasks/task5/src/CarsPage.js
> +let carsList = [
используй const  - этот компонент не меняется

2019-08-27 21:04 UTC, IhorHarashchuk commented on tasks/task5/src/CarsPage.js
> +    .map(car => <Car name={car.name} year={car.year} price={car.price} img={car.img} /> );
лучше разположить вертикально свойства

2019-08-28 06:17 UTC, avramenkop commented on tasks/task5/src/Cars.js
> +import './App.css';
не только к Car, а странице целиком.

2019-08-28 10:48 UTC, IhorHarashchuk commented on tasks/task5/src/Cars.js
> +import './App.css';
тогда общий стиль для всего приложения заиджекти в App.js

2019-08-28 11:56 UTC, avramenkop commented on tasks/task5/public/index.html
> +<div class="root"></div>
есть

2019-08-28 11:56 UTC, avramenkop commented on tasks/task5/src/Cars.js
> +import './App.css';
есть

2019-08-28 11:57 UTC, avramenkop commented on tasks/task5/src/CarsPage.js
> +let carsList = [
есть

2019-08-28 11:57 UTC, avramenkop commented on tasks/task5/src/CarsPage.js
> +    .map(car => <Car name={car.name} year={car.year} price={car.price} img={car.img} /> );
есть

2019-08-28 14:35 UTC, avramenkop commented on tasks/task5/src/CarsPage.js
> +export {CarsPage};
готово

2019-08-29 20:28 UTC, merged